export const theme = {
    colors: {
        primary: "#FF5722",
        primaryDark: "#E64A19",
        secondary: "#2196F3",
        background: "#FAFAFA",
        surface: "#FFFFFF",
        card: "#F5F5F5",
        text: {
            primary: "#212121",
            secondary: "#757575",
            light: "#FFFFFF",
            accent: "#FF5722",
        },
        border: "#E0E0E0",
        success: "#4CAF50",
        error: "#F44336",
        warning: "#FFC107",
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 32,
    },
    borderRadius: {
        xs: 2,
        sm: 4,
        md: 8,
        lg: 12,
        xl: 16,
        full: 999,
    },
};
